insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#036;', 'Dollar');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#3647;', 'Baht');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#8363;', 'Dong');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#8364;', 'Euro');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#8362;', 'New Sheqel');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#8369;', 'Peso');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#163;', 'Pound Sterling');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#82;', 'Rand');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('R&#036;', 'Real');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#8360;', 'Rupee');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#1088;', 'Ruble');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#8361;', 'Won');
insert into sx_currencies(sx_currency_symbol, sx_currency_name) values ('&#165;', 'Yen');
insert into sx_countries(sx_country_name) values ('Australia');
insert into sx_countries(sx_country_name) values ('Brazil');
insert into sx_countries(sx_country_name) values ('Denmark');
insert into sx_countries(sx_country_name) values ('Germany');
insert into sx_countries(sx_country_name) values ('India');
insert into sx_countries(sx_country_name) values ('Israel');
insert into sx_countries(sx_country_name) values ('Japan');
insert into sx_countries(sx_country_name) values ('Mexico');
insert into sx_countries(sx_country_name) values ('Netherlands');
insert into sx_countries(sx_country_name) values ('Russia');
insert into sx_countries(sx_country_name) values ('South Africa');
insert into sx_countries(sx_country_name) values ('South Korea');
insert into sx_countries(sx_country_name) values ('Thailand');
insert into sx_countries(sx_country_name) values ('United States');
insert into sx_countries(sx_country_name) values ('United Kingdom');
insert into sx_countries(sx_country_name) values ('Vietnam');
insert into sx_regions(sx_country_id, sx_region_name) values (1, 'New South Wales');
insert into sx_regions(sx_country_id, sx_region_name) values (1, 'Victoria');
insert into sx_regions(sx_country_id, sx_region_name) values (2, 'Sao Paulo');
insert into sx_regions(sx_country_id, sx_region_name) values (2, 'Rio de Janeiro');
insert into sx_regions(sx_country_id, sx_region_name) values (3, 'Capital Region');
insert into sx_regions(sx_country_id, sx_region_name) values (4, 'Bavaria');
insert into sx_regions(sx_country_id, sx_region_name) values (4, 'Berlin');
insert into sx_regions(sx_country_id, sx_region_name) values (4, 'Hamburg');
insert into sx_regions(sx_country_id, sx_region_name) values (5, 'Maharashtra');
insert into sx_regions(sx_country_id, sx_region_name) values (6, 'Gush Dan');
insert into sx_regions(sx_country_id, sx_region_name) values (7, 'Kansai');
insert into sx_regions(sx_country_id, sx_region_name) values (7, 'Kanto');
insert into sx_regions(sx_country_id, sx_region_name) values (8, 'Federal District');
insert into sx_regions(sx_country_id, sx_region_name) values (9, 'North Holland');
insert into sx_regions(sx_country_id, sx_region_name) values (10, 'Central');
insert into sx_regions(sx_country_id, sx_region_name) values (10, 'Northwestern');
insert into sx_regions(sx_country_id, sx_region_name) values (11, 'Gauteng');
insert into sx_regions(sx_country_id, sx_region_name) values (11, 'Western Cape');
insert into sx_regions(sx_country_id, sx_region_name) values (12, 'Hoseo');
insert into sx_regions(sx_country_id, sx_region_name) values (12, 'National Capital Area');
insert into sx_regions(sx_country_id, sx_region_name) values (13, 'Metropolitan Administration');
insert into sx_regions(sx_country_id, sx_region_name) values (14, 'California');
insert into sx_regions(sx_country_id, sx_region_name) values (14, 'District of Columbia');
insert into sx_regions(sx_country_id, sx_region_name) values (14, 'Florida');
insert into sx_regions(sx_country_id, sx_region_name) values (14, 'Georgia');
insert into sx_regions(sx_country_id, sx_region_name) values (14, 'Nevada');
insert into sx_regions(sx_country_id, sx_region_name) values (14, 'New York');
insert into sx_regions(sx_country_id, sx_region_name) values (14, 'Massachusetts');
insert into sx_regions(sx_country_id, sx_region_name) values (14, 'Washington');
insert into sx_regions(sx_country_id, sx_region_name) values (15, 'England');
insert into sx_regions(sx_country_id, sx_region_name) values (15, 'Scotland');
insert into sx_regions(sx_country_id, sx_region_name) values (16, 'Saigon');
insert into sx_cities(sx_region_id, sx_city_name) values(1, 'Sydney');
insert into sx_cities(sx_region_id, sx_city_name) values(2, 'Melbourne');
insert into sx_cities(sx_region_id, sx_city_name) values(3, 'Sao Paulo');
insert into sx_cities(sx_region_id, sx_city_name) values(4, 'Rio de Janeiro');
insert into sx_cities(sx_region_id, sx_city_name) values(5, 'Copenhagen');
insert into sx_cities(sx_region_id, sx_city_name) values(6, 'Munich');
insert into sx_cities(sx_region_id, sx_city_name) values(7, 'Berlin');
insert into sx_cities(sx_region_id, sx_city_name) values(8, 'Hamburg');
insert into sx_cities(sx_region_id, sx_city_name) values(9, 'Mumbai');
insert into sx_cities(sx_region_id, sx_city_name) values(10, 'Tel Aviv');
insert into sx_cities(sx_region_id, sx_city_name) values(11, 'Osaka');
insert into sx_cities(sx_region_id, sx_city_name) values(12, 'Tokyo');
insert into sx_cities(sx_region_id, sx_city_name) values(13, 'Mexico City');
insert into sx_cities(sx_region_id, sx_city_name) values(14, 'Amsterdam');
insert into sx_cities(sx_region_id, sx_city_name) values(15, 'Moscow');
insert into sx_cities(sx_region_id, sx_city_name) values(16, 'Saint Petersburg');
insert into sx_cities(sx_region_id, sx_city_name) values(17, 'Johannesburg');
insert into sx_cities(sx_region_id, sx_city_name) values(18, 'Cape Town');
insert into sx_cities(sx_region_id, sx_city_name) values(19, 'Daejeon');
insert into sx_cities(sx_region_id, sx_city_name) values(20, 'Seoul');
insert into sx_cities(sx_region_id, sx_city_name) values(21, 'Bangkok');
insert into sx_cities(sx_region_id, sx_city_name) values(22, 'San Francisco');
insert into sx_cities(sx_region_id, sx_city_name) values(22, 'Los Angeles');
insert into sx_cities(sx_region_id, sx_city_name) values(23, 'Washington');
insert into sx_cities(sx_region_id, sx_city_name) values(24, 'Miami');
insert into sx_cities(sx_region_id, sx_city_name) values(25, 'Atlanta');
insert into sx_cities(sx_region_id, sx_city_name) values(26, 'Las Vegas');
insert into sx_cities(sx_region_id, sx_city_name) values(27, 'New York');
insert into sx_cities(sx_region_id, sx_city_name) values(28, 'Boston');
insert into sx_cities(sx_region_id, sx_city_name) values(29, 'Seattle');
insert into sx_cities(sx_region_id, sx_city_name) values(30, 'London');
insert into sx_cities(sx_region_id, sx_city_name) values(30, 'Manchester');
insert into sx_cities(sx_region_id, sx_city_name) values(31, 'Edinburgh');
insert into sx_cities(sx_region_id, sx_city_name) values(32, 'Ho Chi Minh City');


