//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.23 at 09:14:17 AM EDT 
//


package com.euroscripting.dtos;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sx_city_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="location_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sxCityId",
    "locationDesc"
})
@XmlRootElement(name = "locationDTO")
public class LocationDTO
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "sx_city_id")
    protected int sxCityId;
    @XmlElement(name = "location_desc")
    protected String locationDesc;

    /**
     * Gets the value of the sxCityId property.
     * 
     */
    public int getSxCityId() {
        return sxCityId;
    }

    /**
     * Sets the value of the sxCityId property.
     * 
     */
    public void setSxCityId(int value) {
        this.sxCityId = value;
    }

    public boolean isSetSxCityId() {
        return true;
    }

    /**
     * Gets the value of the locationDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationDesc() {
        return locationDesc;
    }

    /**
     * Sets the value of the locationDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationDesc(String value) {
        this.locationDesc = value;
    }

    public boolean isSetLocationDesc() {
        return (this.locationDesc!= null);
    }

}
